name: sc_pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - scanpy>=1.9
  - anndata>=0.9
  - numpy>=1.23
  - pandas>=1.5
  - matplotlib>=3.6
  - seaborn>=0.12
  - jupyter>=1.0
  - ipywidgets>=8.0
  - scipy>=1.9
  - scikit-learn>=1.2
  - python-igraph>=0.10
  - leidenalg>=0.9
  - rpy2>=3.5
  - tzlocal
  - pip>=22.0
  - pip:
      - scrublet>=0.2.3
      - session-info>=1.0
      - adjustText>=0.8